[package]
name = "super-mastermind"
version = "0.1.0"
authors = ["tcatonet <catonethomas@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
colored = "1.6.1"
ansi_term = "0.12.1"
