[package]
name = "super-mastermind"
version = "0.1.0"
authors = ["Lukowskool"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
ansi_term = "0.12.1"
