[package]
name = "super-mastermind"
version = "0.1.0"
authors = ["Yoni <firroloni.yoni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor ="1.1.2"
rand = "0.8.3"